import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: "#f5f5f7" },
  topbar: {
    height: 64,
    paddingHorizontal: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#f5f5f7",
  },
  brand: {
    fontSize: 26,
    fontWeight: "700",
    letterSpacing: -1,
    color: "#1d1d1f",
  },
  brandDot: { color: "#0071e3" },
  searchButton: {
    width: 44,
    height: 44,
    backgroundColor: "#e9e9ed",
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  searchSymbol: { fontSize: 30, color: "#1d1d1f" },
  searchWrap: { paddingHorizontal: 24, paddingBottom: 12 },
  searchInput: {
    height: 48,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: "#e8e8ed",
    fontSize: 17,
    color: "#1d1d1f",
  },
  yellowHero: {
    marginHorizontal: 16,
    marginBottom: 18,
    paddingTop: 30,
    paddingHorizontal: 16,
    borderRadius: 28,
    backgroundColor: "#fff",
    overflow: "hidden",
  },
  new: {
    textAlign: "center",
    color: "#a74100",
    fontWeight: "600",
    fontSize: 12,
    marginBottom: 8,
  },
  heroLabel: {
    textAlign: "center",
    fontSize: 19,
    fontWeight: "600",
    color: "#1d1d1f",
    marginBottom: 12,
  },
  heroTitle: {
    textAlign: "center",
    fontSize: 33,
    lineHeight: 38,
    fontWeight: "700",
    letterSpacing: -0.8,
    color: "#1d1d1f",
  },
  productTag: {
    textAlign: "center",
    fontSize: 14,
    lineHeight: 21,
    color: "#6e6e73",
    marginVertical: 10,
  },
  productTile: {
    backgroundColor: "#fff",
    borderRadius: 26,
    marginHorizontal: 16,
    marginBottom: 18,
    padding: 20,
  },
  productName: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "700",
    letterSpacing: -0.4,
    color: "#1d1d1f",
    textAlign: "center",
  },
  tilePrice: {
    fontSize: 17,
    color: "#1d1d1f",
    fontWeight: "600",
    textAlign: "center",
    marginVertical: 16,
  },
  sheet: { flex: 1, backgroundColor: "#fff" },
  sheetHeader: {
    paddingHorizontal: 24,
    paddingVertical: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  sheetTitle: { fontSize: 22, fontWeight: "700", color: "#1d1d1f", flex: 1 },
  close: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#f0f0f2",
    alignItems: "center",
    justifyContent: "center",
  },
  closeText: { fontSize: 28, color: "#424245" },
  sheetBody: {
    padding: 24,
    paddingTop: 10,
    maxWidth: 650,
    width: "100%",
    alignSelf: "center",
  },
  sheetFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 24,
    borderTopWidth: 1,
    borderColor: "#eee",
    gap: 12,
  },
  price: { fontSize: 26, fontWeight: "700", color: "#1d1d1f" },
  fieldTitle: {
    fontSize: 20,
    fontWeight: "600",
    marginTop: 28,
    marginBottom: 18,
    color: "#1d1d1f",
  },
  muted: { color: "#6e6e73", fontWeight: "400" },
  colors: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  colorRing: {
    width: 46,
    height: 46,
    padding: 5,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: "transparent",
  },
  color: { flex: 1, borderRadius: 20, borderWidth: 1, borderColor: "#0001" },
  selectedRing: { borderColor: "#0071e3", borderWidth: 2 },
  storage: {
    flex: 1,
    minHeight: 58,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#d2d2d7",
    borderRadius: 14,
  },
  storageText: { fontSize: 16, fontWeight: "600", color: "#1d1d1f" },
  sectionCopy: {
    paddingHorizontal: 24,
    fontSize: 15,
    lineHeight: 22,
    color: "#6e6e73",
    marginBottom: 20,
  },
  modelChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingHorizontal: 24,
  },
  chip: {
    paddingHorizontal: 17,
    paddingVertical: 13,
    borderRadius: 24,
    backgroundColor: "#e7e7ec",
    minHeight: 44,
  },
  activeChip: { backgroundColor: "#1d1d1f" },
  chipText: { fontSize: 14, color: "#1d1d1f", fontWeight: "500" },
  difference: { padding: 24, minHeight: 44 },
  compareRow: { flexDirection: "row", gap: 16 },
  compareCell: { flex: 1 },
  compareName: {
    fontSize: 16,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 12,
    color: "#1d1d1f",
  },
  specRow: { paddingVertical: 20, borderTopWidth: 1, borderColor: "#e6e6eb" },
  specLabel: {
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.7,
    color: "#6e6e73",
    marginBottom: 12,
  },
  specValue: {
    flex: 1,
    textAlign: "center",
    fontSize: 14,
    lineHeight: 20,
    color: "#1d1d1f",
  },
  tabbar: {
    flexDirection: "row",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: "#d2d2d7",
    backgroundColor: "#fff",
    paddingTop: 10,
  },
  tab: {
    flex: 1,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  tabIcon: { fontSize: 23, color: "#747478" },
  tabLabel: { fontSize: 10, fontWeight: "600", color: "#747478" },
  activeTab: { color: "#0071e3" },
});
