/* Original Figma assets, bundled locally. */
export const assets = {
  "accessories/imgFigure": "accessories-imgFigure.png",
  "accessories/imgFigure1": "accessories-imgFigure1.png",
  "accessories/imgFigure2": "accessories-imgFigure2.png",
  "chapter-nav/imgIphone14ProLightDfhcc00Ur2OiLargeSvg":
    "chapter-nav-imgIphone14ProLightDfhcc00Ur2OiLargeSvg.svg",
  "chapter-nav/imgIphone14LightFwknsxkf80UqLargeSvg":
    "chapter-nav-imgIphone14LightFwknsxkf80UqLargeSvg.svg",
  "chapter-nav/imgIphone13LightEwo3E0Sf67O2LargeSvg":
    "chapter-nav-imgIphone13LightEwo3E0Sf67O2LargeSvg.svg",
  "chapter-nav/imgIphoneSeLightFhg8Duy6FfauLargeSvg":
    "chapter-nav-imgIphoneSeLightFhg8Duy6FfauLargeSvg.svg",
  "chapter-nav/imgIphone12LightCxh2Ll1Zwpw2LargeSvg":
    "chapter-nav-imgIphone12LightCxh2Ll1Zwpw2LargeSvg.svg",
  "chapter-nav/imgIphoneCompareLightF4Jj7Brpbvm2LargeSvg":
    "chapter-nav-imgIphoneCompareLightF4Jj7Brpbvm2LargeSvg.svg",
  "chapter-nav/imgAirpodsLight8Oj157P2476ALargeSvg":
    "chapter-nav-imgAirpodsLight8Oj157P2476ALargeSvg.svg",
  "chapter-nav/imgAirtagLightCb2Bmnv6AoeuLargeSvg":
    "chapter-nav-imgAirtagLightCb2Bmnv6AoeuLargeSvg.svg",
  "chapter-nav/imgAccessoriesLightEd5L6IpsevquLargeSvg":
    "chapter-nav-imgAccessoriesLightEd5L6IpsevquLargeSvg.svg",
  "chapter-nav/imgGroup": "chapter-nav-imgGroup.svg",
  "chapter-nav/imgGroup1": "chapter-nav-imgGroup1.svg",
  "chapter-nav/imgShopIphoneLightB2ToggskllleLargeSvg":
    "chapter-nav-imgShopIphoneLightB2ToggskllleLargeSvg.svg",
  "comparison/imgFigure": "comparison-imgFigure.png",
  "comparison/imgIPhone14ProAvailableInDeepPurpleGoldSilverAndSpaceBlack":
    "comparison-imgIPhone14ProAvailableInDeepPurpleGoldSilverAndSpaceBlack.png",
  "comparison/imgFigure1": "comparison-imgFigure1.png",
  "comparison/imgFigure2": "comparison-imgFigure2.png",
  "comparison/imgFigure3": "comparison-imgFigure3.png",
  "comparison/imgFigure4": "comparison-imgFigure4.png",
  "comparison/imgFigure5": "comparison-imgFigure5.png",
  "comparison/imgFigure6": "comparison-imgFigure6.png",
  "comparison/imgFigure7": "comparison-imgFigure7.png",
  "comparison/imgFigure8": "comparison-imgFigure8.png",
  "comparison/imgFigure9": "comparison-imgFigure9.png",
  "comparison/imgFigure10": "comparison-imgFigure10.png",
  "comparison/imgIPhone14AvailableInBluePurpleYellowMidnightStarlightAndProductRed":
    "comparison-imgIPhone14AvailableInBluePurpleYellowMidnightStarlightAndProductRed.png",
  "comparison/imgFigure11": "comparison-imgFigure11.png",
  "comparison/imgFigure12": "comparison-imgFigure12.png",
  "comparison/imgFigure13": "comparison-imgFigure13.png",
  "comparison/imgFigure14": "comparison-imgFigure14.png",
  "comparison/imgIPhone13AvailableInGreenPinkBlueMidnightStarlightAndProductRed":
    "comparison-imgIPhone13AvailableInGreenPinkBlueMidnightStarlightAndProductRed.png",
  "comparison/imgFigure15": "comparison-imgFigure15.png",
  "comparison/imgFigure16": "comparison-imgFigure16.png",
  "comparison/imgFigure17": "comparison-imgFigure17.png",
  "comparison/imgIPhoneSeAvailableInMidnightStarlightAndProductRed":
    "comparison-imgIPhoneSeAvailableInMidnightStarlightAndProductRed.png",
  "comparison/imgFigure18": "comparison-imgFigure18.png",
  "comparison/imgFigure19": "comparison-imgFigure19.png",
  "comparison/imgFigure20": "comparison-imgFigure20.png",
  "ecosystem/imgFigure": "ecosystem-imgFigure.png",
  "ecosystem/imgH2": "ecosystem-imgH2.png",
  "ecosystem/imgH3": "ecosystem-imgH3.png",
  "ecosystem/imgLi": "ecosystem-imgLi.png",
  "ecosystem/imgLi1": "ecosystem-imgLi1.png",
  "ecosystem/imgLi2": "ecosystem-imgLi2.png",
  "ecosystem/imgLi3": "ecosystem-imgLi3.png",
  "ecosystem/imgLi4": "ecosystem-imgLi4.png",
  "ecosystem/imgLi5": "ecosystem-imgLi5.png",
  "ecosystem/imgLi6": "ecosystem-imgLi6.png",
  "ecosystem/imgMusicAlbumLeftErm7O9E8F9MeLargeJpg":
    "ecosystem-imgMusicAlbumLeftErm7O9E8F9MeLargeJpg.png",
  "ecosystem/imgMusicAlbumMiddleEo1Xuly5GmqaLargeJpg":
    "ecosystem-imgMusicAlbumMiddleEo1Xuly5GmqaLargeJpg.png",
  "ecosystem/imgMusicAlbumRightCtoplsymatsiLargeJpg":
    "ecosystem-imgMusicAlbumRightCtoplsymatsiLargeJpg.png",
  "ecosystem/imgDiv": "ecosystem-imgDiv.png",
  "ecosystem/imgDiv1": "ecosystem-imgDiv1.png",
  "ecosystem/imgDiv2": "ecosystem-imgDiv2.png",
  "ecosystem/imgDiv3": "ecosystem-imgDiv3.png",
  "ecosystem/imgDiv4": "ecosystem-imgDiv4.png",
  "ecosystem/imgFigure1": "ecosystem-imgFigure1.png",
  "ecosystem/imgDiv5": "ecosystem-imgDiv5.png",
  "ecosystem/imgFigure2": "ecosystem-imgFigure2.png",
  "ecosystem/imgFigure3": "ecosystem-imgFigure3.png",
  "ecosystem/imgAppleMusicLogo": "ecosystem-imgAppleMusicLogo.svg",
  "footer/imgSeperator": "footer-imgSeperator.svg",
  "footer/imgSeperator1": "footer-imgSeperator1.svg",
  "footer/imgApple": "footer-imgApple.svg",
  "footer/imgApple1": "footer-imgApple1.svg",
  "footer/imgApple2": "footer-imgApple2.svg",
  "footer/imgApple3": "footer-imgApple3.svg",
  "global-nav/imgFrame": "global-nav-imgFrame.svg",
  "global-nav/imgFrame1": "global-nav-imgFrame1.svg",
  "global-nav/imgFrame2": "global-nav-imgFrame2.svg",
  "global-nav/imgFrame3": "global-nav-imgFrame3.svg",
  "global-nav/imgFrame4": "global-nav-imgFrame4.svg",
  "global-nav/imgFrame5": "global-nav-imgFrame5.svg",
  "global-nav/imgFrame6": "global-nav-imgFrame6.svg",
  "global-nav/imgFrame7": "global-nav-imgFrame7.svg",
  "global-nav/imgFrame8": "global-nav-imgFrame8.svg",
  "global-nav/imgFrame9": "global-nav-imgFrame9.svg",
  "global-nav/imgFrame10": "global-nav-imgFrame10.svg",
  "global-nav/imgFrame11": "global-nav-imgFrame11.svg",
  "global-nav/imgFrame12": "global-nav-imgFrame12.svg",
  "heroes/imgFigure": "heroes-imgFigure.png",
  "heroes/imgFigure1": "heroes-imgFigure1.png",
  "heroes/imgFigure2": "heroes-imgFigure2.png",
  "heroes/imgFigure3": "heroes-imgFigure3.png",
  "heroes/imgFigure4": "heroes-imgFigure4.png",
  "heroes/imgFigure5": "heroes-imgFigure5.png",
  "savings/imgFigure": "savings-imgFigure.png",
  "savings/imgH4": "savings-imgH4.png",
  "savings/imgH5": "savings-imgH5.png",
  "savings/imgH6": "savings-imgH6.png",
  "savings/imgFigure1": "savings-imgFigure1.png",
  "savings/imgDiv": "savings-imgDiv.png",
  "services/imgFigure": "services-imgFigure.png",
  "services/imgFigure1": "services-imgFigure1.png",
  "services/imgFigure2": "services-imgFigure2.png",
  "tour/imgFigure": "tour-imgFigure.png",
  "why-iphone/imgDiv": "why-iphone-imgDiv.png",
  "why-iphone/imgFigure": "why-iphone-imgFigure.png",
} as const;
export type AssetKey = keyof typeof assets;
